name: maptes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  model_viewer_plus: ^1.7.2
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/icon/icon.png
    - assets/json/markerdata.json
    - assets/maptest.glb
    - assets/splash/mapsplash.png
    - assets/swulogo.png
    - assets/icon/icon_ios.png
    - assets/icon/icon_android.png
    - assets/logo.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_android.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  macos:
    generate: true
    image_path: "assets/icon/icon_android.png"


flutter_native_splash:
  color: "#ffffff"
  image: "assets/swulogo.png"
  android_12:
    image: "assets/swulogo.png"
    color: "#ffffff"

  #background_image_android: "assets/newlogo.png"
  #background_image_dark_android: "assets/newlogo.png"
  #background_image_ios: "assets/newlogo.png"
  #background_image_dark_ios: "assets/newlogo.png"
  web: false
  android: true
  ios: true

